### ISSUE TITLE
Corruption on Rezurrection final screen

### ISSUE THREAD

**Issue by ikjordan** [SegHaxx/sz81#1]
SZ81 is a great emulator - thank you for supporting it.

I have noticed issues on the final screen of the  rezurrection demo. 
1) The text "Calodox we own ZX81" intermittently becomes corrupted as it scrolls up screen (an issue with rowcounter?). I've attached a screen shot.
2) The image continues to move up and down by 1 line, after the scrolling completes

Neither effect occurs on my WRX modded "real" 16kB ZX81. It also does not occur on the latest version of EightyOne (after the changes to model the  video flip flops in 1.29).

I've hacked together a minimal example (`head.p`) using the source code `(head.asm`) and compiling with ZX-IDE. 
The files are zipped and attached. I hope they can shed some light, so far I've not had a breakthrough, after looking at the code for an afternoon! 

Thanks again for a great emulator.

![head](https://github.com/SegHaxx/sz81/assets/38705261/c762c58a-5d6b-4257-ac60-6cd118dba297)

[FASMW-ZX.zip](https://github.com/SegHaxx/sz81/files/12292163/FASMW-ZX.zip)

**Comment by ikjordan** [comment]
I spend some time working through the rezzurection code. It is quite unusual. Some points I noted:

1. It is ending VSYNC close to the wrap point for `hsync_counter`. 
2. It is displaying an interlaced image, at roughly 52Hz
3. It takes advantage of the blank rows at the top and bottom of normal characters, by design `rowcounter` starts at 1 on the lower interlaced line. This can be seen on a real ZX81 by replacing one of the characters with a ZX81 graphic that uses all 8 rows.

It appears the VSYNC towards the wrap point of the `hsync_counter` is causing the issue. I can get SZ81 to behave in a similar way to my real ZX81 by adding a check that holds the `rowcounter` at 0 for 1 more line, if VSYNC is lowered when `hsync_counter` > 178.

Alternatively, if the delay code in `head.p` is extended, so that VSYNC is moved to coincide with HSYNC, then the issue also goes away.

So there is a "hack" to fix it. I took a quick look at the latest EightyOne code. There is code to handle a case where VSYNC goes low before HSYNC, so perhaps this change does match the real hardware behaviour? it would be good to understand how it relates to real hardware. I took a quick look at the latest EightyOne code. There is code to handle a case where VSYNC goes low before HSYNC, so perhaps this change does match the real hardware behaviour?

**Comment by SegHaxx** [comment]
Hi, I'll note I have little expertise in the ZX platform and only have begun dabbling in the Z80. So I can't currently be much help fixing deep hardware voodoo.

I'd like to obtain a ZX Spectrum but it appears they were never actually sold in the US and thus are hard to get here, however the Timex Sinclair 1000 was fairly successful and is easily obtainable, but life happened and that whole project has been backburnered for now.

I went looking for an emulator that would run on a Raspi 4 and it was surprisingly hard to find this one, so I git converted the old repo then put the E.Olofsen releases on top of that before it all disappeared. I've actually been meaning to re-do this so my name isn't on the commits...

Anyway if anyone else can figure this out let me know.

**Comment by ikjordan** [comment]
No problem, thank you for archiving the source code. The work around does fix it, the challenge is to justify it from a hardware perspective!

I'll ask on https://www.sinclairzxworld.com/ 

If you don't mind, I'll leave the issue open for a little while longer, so I can post any information that comes back from the forum here.

**Comment by ikjordan** [comment]
I think the discussion on https://www.sinclairzxworld.com/ has completed. 
There is no definitive hardware justification, but the workaround does fix the problem. Therefore closing the issue
